Add optional allocation counter
trezor/micropython pull request #3
Opened 2020-10-26 21:54 UTC by mmilata

Add counter of allocations for tracking memory usage - see trezor/trezor-firmware#1324 for more information. The feature is off by default and has to be explicitly enabled at build time.

2020-10-26 22:03 UTC, prusnak requested changes
Concept ACK. I suggested small changes around variable type. If we need to track more than 2 billions of allocations I suggest to switch the type to `unsigned long long` and function integer-to-object function to `mp_obj_new_int_from_ull`.

2020-10-26 22:03 UTC, prusnak commented on py/gc.c
> +uint64_t alloc_count = 0;
```suggestion
mp_uint_t alloc_count = 0;
```

2020-10-26 22:03 UTC, prusnak commented on py/gc.h
> +extern uint64_t alloc_count;
```suggestion
extern mp_uint_t alloc_count;
```

2020-10-26 22:03 UTC, prusnak commented on py/modmicropython.c
> +    return mp_obj_new_int(alloc_count);
```suggestion
    return mp_obj_new_int_from_uint(alloc_count);
```

2020-10-27 12:21 UTC, mmilata commented
Updated. Device tests do <100 millions allocations total so there's quite a margin and if we wanted we can detect the counter overflowing -  `mp_uint_t` is fine.

2020-10-27 12:24 UTC, merged

2020-10-27 12:24 UTC, prusnak commented
Merged, thanks!